### ISSUE TITLE
Delegation Manager should have its own repo

### ISSUE THREAD

**Issue by Iamscaredofcode** [multiversx/mx-deprecated-starter-dapp#57]
Hi

to keep things nice and tidy I'd advocate for placing the delegation manager into its own repository.

This wouldn't only boost the repo's SEO, but also the projects maturity as it isn't really an example/starter dapp anymore.

**Comment by lonnie-allstar** [comment]
+1 - Echoing Iamscaredofcode's sentiments.

**Comment by newtmex** [comment]
g

**Comment by newtmex** [comment]
I agree with @Iamscaredofcode. Most of us that would want to customize the code will not want to worry about other starter templates in this repo. We will just want to fork this repo, create our custom branch and deploy that branch to our host server.

**Comment by newtmex** [comment]
I guess this https://github.com/ElrondNetwork/delegation-dashboard.elrond.com closes this issue :)

**Comment by iulianpascalau** [comment]
Deprecated repo, will close for now. Thanks for reporting this issue.
